
/* Generated by Interface Builder */

#import "InfoObject.h"
#import <appkit/appkit.h>

@implementation InfoObject

- showInfoPanel:sender
{
    if(!InfoPanel)
		[NXApp loadNibSection:"InfoObject.nib" owner:self];
   	if(!InfoPanel)
    	NXRunAlertPanel("Show Infopanel","Error loading Nib-file !","Cancel",NULL,NULL);
	[InfoPanel makeKeyAndOrderFront:self];
	return self;
}


@end
